export const NAKSHATRAS = [
  { index: 0, name: 'Ashwini', gana: 'Deva', yoni: 'Ashwa', nadi: 'Vata', lord: 'Ketu' },
  { index: 1, name: 'Bharani', gana: 'Manushya', yoni: 'Gaja', nadi: 'Pitta', lord: 'Venus' },
  { index: 2, name: 'Krittika', gana: 'Rakshasa', yoni: 'Mesha', nadi: 'Kapha', lord: 'Sun' },
  { index: 3, name: 'Rohini', gana: 'Manushya', yoni: 'Sarpa', nadi: 'Kapha', lord: 'Moon' },
  { index: 4, name: 'Mrigashira', gana: 'Deva', yoni: 'Sarpa', nadi: 'Pitta', lord: 'Mars' },
  { index: 5, name: 'Ardra', gana: 'Manushya', yoni: 'Shwana', nadi: 'Vata', lord: 'Rahu' },
  { index: 6, name: 'Punarvasu', gana: 'Deva', yoni: 'Marjara', nadi: 'Vata', lord: 'Jupiter' },
  { index: 7, name: 'Pushya', gana: 'Deva', yoni: 'Mesha', nadi: 'Pitta', lord: 'Saturn' },
  { index: 8, name: 'Ashlesha', gana: 'Rakshasa', yoni: 'Marjara', nadi: 'Kapha', lord: 'Mercury' },
  { index: 9, name: 'Magha', gana: 'Rakshasa', yoni: 'Mushaka', nadi: 'Kapha', lord: 'Ketu' },
  { index: 10, name: 'Purva Phalguni', gana: 'Manushya', yoni: 'Mushaka', nadi: 'Pitta', lord: 'Venus' },
  { index: 11, name: 'Uttara Phalguni', gana: 'Manushya', yoni: 'Gau', nadi: 'Vata', lord: 'Sun' },
  { index: 12, name: 'Hasta', gana: 'Deva', yoni: 'Mahisha', nadi: 'Vata', lord: 'Moon' },
  { index: 13, name: 'Chitra', gana: 'Rakshasa', yoni: 'Vyaghra', nadi: 'Pitta', lord: 'Mars' },
  { index: 14, name: 'Swati', gana: 'Deva', yoni: 'Mahisha', nadi: 'Kapha', lord: 'Rahu' },
  { index: 15, name: 'Vishakha', gana: 'Rakshasa', yoni: 'Vyaghra', nadi: 'Kapha', lord: 'Jupiter' },
  { index: 16, name: 'Anuradha', gana: 'Deva', yoni: 'Mriga', nadi: 'Pitta', lord: 'Saturn' },
  { index: 17, name: 'Jyeshtha', gana: 'Rakshasa', yoni: 'Mriga', nadi: 'Vata', lord: 'Mercury' },
  { index: 18, name: 'Mula', gana: 'Rakshasa', yoni: 'Shwana', nadi: 'Kapha', lord: 'Ketu' },
  { index: 19, name: 'Purva Ashadha', gana: 'Manushya', yoni: 'Vanara', nadi: 'Pitta', lord: 'Venus' },
  { index: 20, name: 'Uttara Ashadha', gana: 'Manushya', yoni: 'Nakula', nadi: 'Vata', lord: 'Sun' },
  { index: 21, name: 'Shravana', gana: 'Deva', yoni: 'Vanara', nadi: 'Kapha', lord: 'Moon' },
  { index: 22, name: 'Dhanishta', gana: 'Rakshasa', yoni: 'Simha', nadi: 'Pitta', lord: 'Mars' },
  { index: 23, name: 'Shatabhisha', gana: 'Rakshasa', yoni: 'Ashwa', nadi: 'Vata', lord: 'Rahu' },
  { index: 24, name: 'Purva Bhadrapada', gana: 'Manushya', yoni: 'Simha', nadi: 'Vata', lord: 'Jupiter' },
  { index: 25, name: 'Uttara Bhadrapada', gana: 'Manushya', yoni: 'Gau', nadi: 'Pitta', lord: 'Saturn' },
  { index: 26, name: 'Revati', gana: 'Deva', yoni: 'Gaja', nadi: 'Kapha', lord: 'Mercury' },
] as const;

export const RASHIS = [
  { index: 0, name: 'Aries', lord: 'Mars', varna: 'Kshatriya', vashya: 'Quadruped' },
  { index: 1, name: 'Taurus', lord: 'Venus', varna: 'Vaishya', vashya: 'Quadruped' },
  { index: 2, name: 'Gemini', lord: 'Mercury', varna: 'Shudra', vashya: 'Human' },
  { index: 3, name: 'Cancer', lord: 'Moon', varna: 'Brahmin', vashya: 'Water' },
  { index: 4, name: 'Leo', lord: 'Sun', varna: 'Kshatriya', vashya: 'Forest' },
  { index: 5, name: 'Virgo', lord: 'Mercury', varna: 'Vaishya', vashya: 'Human' },
  { index: 6, name: 'Libra', lord: 'Venus', varna: 'Shudra', vashya: 'Human' },
  { index: 7, name: 'Scorpio', lord: 'Mars', varna: 'Brahmin', vashya: 'Water' },
  { index: 8, name: 'Sagittarius', lord: 'Jupiter', varna: 'Kshatriya', vashya: 'Forest' },
  { index: 9, name: 'Capricorn', lord: 'Saturn', varna: 'Vaishya', vashya: 'Quadruped' },
  { index: 10, name: 'Aquarius', lord: 'Saturn', varna: 'Shudra', vashya: 'Human' },
  { index: 11, name: 'Pisces', lord: 'Jupiter', varna: 'Brahmin', vashya: 'Water' },
] as const;

export const PLANET_FRIENDSHIPS: Record<string, { friends: string[], neutrals: string[], enemies: string[] }> = {
  Sun:     { friends: ['Moon','Mars','Jupiter'],    neutrals: ['Mercury'],           enemies: ['Venus','Saturn','Rahu','Ketu'] },
  Moon:    { friends: ['Sun','Mercury'],            neutrals: ['Mars','Jupiter','Venus','Saturn'], enemies: ['Rahu','Ketu'] },
  Mars:    { friends: ['Sun','Moon','Jupiter'],     neutrals: ['Venus','Saturn'],    enemies: ['Mercury','Rahu','Ketu'] },
  Mercury: { friends: ['Sun','Venus'],              neutrals: ['Mars','Jupiter','Saturn'], enemies: ['Moon','Rahu','Ketu'] },
  Jupiter: { friends: ['Sun','Moon','Mars'],        neutrals: ['Saturn'],            enemies: ['Mercury','Venus','Rahu','Ketu'] },
  Venus:   { friends: ['Mercury','Saturn'],         neutrals: ['Mars','Jupiter'],    enemies: ['Sun','Moon','Rahu','Ketu'] },
  Saturn:  { friends: ['Mercury','Venus'],          neutrals: ['Jupiter'],           enemies: ['Sun','Moon','Mars','Rahu','Ketu'] },
  Rahu:    { friends: ['Venus','Saturn'],           neutrals: ['Mercury','Jupiter'], enemies: ['Sun','Moon','Mars','Ketu'] },
  Ketu:    { friends: ['Mars','Venus'],             neutrals: ['Saturn','Mercury'],  enemies: ['Sun','Moon','Jupiter','Rahu'] },
};
